"""Re-run the passing conditions against phonotactics-preserving (Markov) fake
lexicons, after checking that planted Tamil still passes against them.
    FAKE_KIND=markov python markov_test.py
"""
import sys
from multiprocessing import Pool

import indus_core as C
import run_all as RA
import synth

assert C.FAKE_KIND == "markov", "run with FAKE_KIND=markov"


def prebuild(args):
    lang, seed = args
    C.fake_forms(C.load_lexicon(lang), "full", seed)


def main(which):
    RA.log(f"## Markov-null tests ({RA.now()}): fake lexicons generated by a 2-letter-context "
           "character model trained on the real lexicon (same size, same length distribution)")
    texts = C.unique_texts(C.load_corpus())
    with Pool(4) as pool:
        langs = sorted({w.split("-")[-1] if w.startswith("planted") else w.split("-")[0] for w in which})
        pool.map(prebuild, [(l, s) for l in langs for s in list(range(20_000, 20_030)) + list(range(10_000, 10_030))], chunksize=1)
        for w in which:
            if w.startswith("planted"):
                _, noise, lang = w.split("-")
                pt, _ = synth.planted_corpus(texts, C.load_lexicon(lang), seed=7, noise=float(noise))
                tr, he = C.split_texts(pt)
                ctrl = True
            else:
                lang = w.split("-")[0]
                tx = C.unique_texts(C.load_im77_corpus()) if w.endswith("im77") else texts
                tr, he = C.split_texts(tx)
                ctrl = False
            top = [s for s, _ in C.sign_freq(tr).most_common()]
            RA.run_condition(pool, f"markov-{w}-full-80", lang, "full", 80, tr, he, top, 20, 30,
                             32_000, control=ctrl)


if __name__ == "__main__":
    main(sys.argv[1:] or ["planted-0.0-tamil", "planted-0.2-tamil", "tamil", "sanskrit",
                          "tamil-im77", "english"])
