"""Strategy 51: non-local constraints. For frequent sign pairs, co-occurrence within a text (non-adjacent)
in real texts vs texts generated by the Indus bigram chain (10 runs, same length distribution).
Pairs far below / above the bigram expectation are long-distance syntax (exclusivity, agreement)."""
import csv, collections, random, itertools, math
T=[]
for r in csv.DictReader(open('data/im77/im77_corpus_lines.csv')):
    t=tuple(r['signs_clean'].split())
    if '0' not in t and len(t)>=3: T.append(t)
U=list(set(T))
tr=collections.defaultdict(list)
for t in U:
    s=('^',)+t+('$',)
    for a,b in zip(s,s[1:]): tr[a].append(b)
rng=random.Random(0)
def gen(L):
    while True:
        s=['^']
        while s[-1]!='$' and len(s)<L+2: s.append(rng.choice(tr[s[-1]]))
        if s[-1]=='$' and len(s)==L+2: return tuple(s[1:-1])
freq=collections.Counter(x for t in U for x in set(t)); top=[x for x,n in freq.items() if n>=40]
def co(C):
    c=collections.Counter()
    for t in C:
        s=set(t)
        for a,b in itertools.combinations(sorted(x for x in s if x in top),2):
            # non-adjacent only
            if not any((t[i],t[i+1]) in ((a,b),(b,a)) for i in range(len(t)-1)): c[(a,b)]+=1
    return c
real=co(U); R=10; sims=[co([gen(len(t)) for t in U]) for _ in range(R)]
res=[]
for p in set(real)|set().union(*sims):
    m=sum(s[p] for s in sims)/R; sd=math.sqrt(sum((s[p]-m)**2 for s in sims)/(R-1))+0.5
    res.append(((real[p]-m)/sd,p,real[p],m))
res.sort()
print('AVOIDED beyond bigram:'); [print(f"  M{a}~M{b} real {r} bigram {m:.1f} z {z:.1f}") for z,(a,b),r,m in res[:12] if m>=5]
print('ATTRACTED beyond bigram:'); [print(f"  M{a}~M{b} real {r} bigram {m:.1f} z {z:.1f}") for z,(a,b),r,m in res[::-1][:12]]
