"""v20 cycle 5: what makes the held-out line conservation? Two more resynthesis controls in the ZL layout, each
run through the same held-out test (cycle 3c):
  wordbigram: each line regenerated by a word-level bigram chain trained on its own stratum (first word from the
     stratum's line-initial words; next word from the bigram successors of the previous word, backoff to unigram).
     Keeps word-to-word junction dependencies, no width, no quota.
  shufline: words shuffled inside each line (keeps each line's exact word multiset, so any per-line conserved
     count is kept by construction; this is a sanity ceiling: should reproduce the ratio).
  shufpage_len: words dealt across the lines of a page but each line refilled to its original GLYPH length as
     closely as possible (greedy), i.e. a pure 'line filled to a width in glyphs' text with no other constraint.
Plus (b) the relative-dispersion soft-quota detector over the cycle-1 checkpoints."""
import sys, os, json, random
import numpy as np
from collections import Counter, defaultdict
from multiprocessing import Pool
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import v20_lib as L
import v20_cycle3 as C3


def wordbigram(C, seed=1):
    rng = random.Random(seed)
    big = defaultdict(lambda: defaultdict(Counter)); first = defaultdict(Counter); uni = defaultdict(Counter)
    for Ln in C.lines:
        s = Ln['stratum']; ws = Ln['words']
        first[s][ws[0]] += 1
        for a, b in zip(ws, ws[1:]): big[s][a][b] += 1
        for w in ws: uni[s][w] += 1
    def draw(c): ks, vs = zip(*c.items()); return rng.choices(ks, vs)[0]
    lines = []
    for Ln in C.lines:
        s = Ln['stratum']; out = [draw(first[s])]
        while len(out) < len(Ln['words']):
            nxt = big[s].get(out[-1])
            out.append(draw(nxt) if nxt and rng.random() < 0.9 else draw(uni[s]))
        lines.append(dict(Ln, words=out))
    return L.Corpus(lines, C.name + '-wordbigram', True)


def shufline(C, seed=1):
    rng = random.Random(seed); lines = []
    for Ln in C.lines:
        ws = list(Ln['words']); rng.shuffle(ws); lines.append(dict(Ln, words=ws))
    return L.Corpus(lines, C.name + '-shufline', True)


def shufpage_len(C, seed=1):
    """refill each page's lines from its shuffled word pool so that each line's glyph length matches the original."""
    rng = random.Random(seed); bypage = defaultdict(list)
    for i, Ln in enumerate(C.lines): bypage[Ln['page']].append(i)
    new = [None] * len(C.lines)
    for p, idx in bypage.items():
        pool = [w for i in idx for w in C.lines[i]['words']]; rng.shuffle(pool)
        for i in idx:
            target = sum(len(L.vlib.glyphs(w)) for w in C.lines[i]['words']); n = len(C.lines[i]['words'])
            out = []
            for k in range(n):
                if not pool: break
                rem = target - sum(len(L.vlib.glyphs(w)) for w in out); slots = n - k
                want = rem / slots
                j = min(range(min(len(pool), 40)), key=lambda j: abs(len(L.vlib.glyphs(pool[j])) - want))
                out.append(pool.pop(j))
            new[i] = dict(C.lines[i], words=out or C.lines[i]['words'][:1])
    return L.Corpus([x for x in new if x['words']], C.name + '-widthfill', True)


SYN = {'wordbigram': wordbigram, 'shufline': shufline, 'widthfill': shufpage_len}


def job(kind):
    out = os.path.join(L.CK, 'c5_%s.json' % kind)
    if os.path.exists(out): return json.load(open(out))
    if kind == 'b':
        r = C3.part_b(); json.dump(r, open(out, 'w')); return {'b': 'done'}
    C = L.voynich_corpus(); S = SYN[kind](C)
    orig = C3.load; C3.load = lambda spec: S
    try: r = C3.part_c(dict(name=kind, src='voy'))
    finally: C3.load = orig
    json.dump(r, open(out, 'w'), indent=1)
    return r


if __name__ == '__main__':
    with Pool(2) as P:
        for r in P.imap_unordered(job, ['wordbigram', 'widthfill', 'shufline', 'b']):
            print(r, flush=True)
