"""v31 cycle 4: SPELL VOCABULARY THROUGH A COPY-AND-VARY PROCEDURE.

If the Voynich is not spell-like in texture but generator-like, could it be spell words run through a
procedure? Random search: thousands of copy-and-vary procedures (window, mutation rate, fresh-word rate,
edits per copy) fed with four vocabularies (voces magicae, Latin, hand-written gibberish, Pinyin). Each
candidate is scored by its distance to the Voynich on a random half of the features (selection) and judged on
the other half (held out). Planted control: targets generated by the same procedure from a known vocabulary
with hidden parameters must be traced back to that vocabulary.
"""
import os, sys, json, random
import numpy as np
from collections import Counter, defaultdict
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import v31_lib as L, v31_cycle1 as C1
from multiprocessing import Pool

N = 100
FN = 'v31_cycle4.txt'
NC = int(os.environ.get('V31_NC', 300))   # candidates per vocabulary


def vocab_sources():
    C = json.load(open(L.CORPORA))
    def toks(pred): return [w for k, v in C.items() if pred(k, v) for d in v['docs'] for l in d for w in l]
    return {'MAGIC': toks(lambda k, v: v['cls'] == 'MAGIC'),
            'LATIN': toks(lambda k, v: k == 'L_Isidore')[:20000],
            'GIBB': toks(lambda k, v: v['cls'] == 'GIBB'),
            'PINYIN': toks(lambda k, v: k == 'L_ChinesePin_Lite')[:20000]}


def procedure(src, prm, seed, n=700):
    rng = random.Random(seed)
    w, pm, pf, ne, start = prm['w'], prm['pm'], prm['pf'], prm['ne'], prm['start']
    al = Counter(c for x in src[:5000] for c in x); ak, av = list(al), list(al.values())
    pos = (start + seed * 7919) % max(1, len(src) - 2000)
    out = [src[pos + i] for i in range(5)]; pos += 5
    while len(out) < n:
        if rng.random() < pf:
            x = src[pos % len(src)]; pos += 1
        else:
            x = rng.choice(out[-w:])
            if rng.random() < pm:
                for _ in range(rng.randint(1, ne)):
                    i = rng.randrange(len(x)); r = rng.random()
                    if r < 0.6: x = x[:i] + rng.choices(ak, av)[0] + x[i + 1:]
                    elif r < 0.8 and len(x) < 12: x = x[:i] + rng.choices(ak, av)[0] + x[i:]
                    elif len(x) > 2: x = x[:i] + x[i + 1:]
        out.append(x)
    lines = []; i = 0
    while i < len(out):
        k = rng.randint(7, 11); lines.append(out[i:i + k]); i += k
    return lines


def rand_prm(rng):
    return {'w': rng.choice([3, 5, 10, 20, 40, 80, 150]), 'pm': rng.random(), 'pf': rng.random() * 0.7,
            'ne': rng.choice([1, 1, 2, 3]), 'start': rng.randrange(10 ** 6)}


def work(a):
    src_name, h, prm, seed, keys = a
    S = SRC[src_name]
    lines = procedure(S, prm, seed)
    samp = L.samples([lines], N=N, maxs=6)
    rng = random.Random(seed)
    F = []
    for s in samp:
        f = L.features(s, rng); F.append([f[k] for k in keys])
    F = np.array(F, float)
    F[~np.isfinite(F)] = 0
    return src_name, h, prm, np.median(F, 0).tolist()


SRC = None


def main():
    global SRC
    SRC = vocab_sources()
    R, keys, X, corp, cls = C1.load(N)
    tr = np.isin(cls, L.CLASSES)
    corpora = sorted(set(corp[tr]))
    cm = np.array([np.median(X[corp == c], 0) for c in corpora])
    scale = np.median(np.abs(cm - np.median(cm, 0)), 0) + 1e-6      # robust spread of corpus medians
    target = {'V_ZL': np.median(X[corp == 'V_ZL'], 0), 'V_IT': np.median(X[corp == 'V_IT'], 0)}
    rng = random.Random(11)
    jobs = []
    for s in SRC:
        for h in range(NC):
            jobs.append((s, h, rand_prm(rng), rng.randrange(10 ** 6), keys))
    # planted targets: two hidden-parameter runs per vocabulary (not among the candidates)
    with Pool(2, initializer=_init) as p:
        Rc = []
        for i, r in enumerate(p.imap_unordered(work, jobs, chunksize=2)):
            Rc.append(r)
            if i % 40 == 0: print('candidates', i, flush=True)
        pl_jobs = [(s, -1, rand_prm(random.Random(900 + i)), 777 + i, keys) for i, s in enumerate(SRC) for _ in range(2)]
        Pl = p.map(work, pl_jobs)
    for i, r in enumerate(Pl): target[f'P_{r[0]}_{i % 2}'] = np.array(r[3])
    feats = np.array([r[3] for r in Rc]); srcs = np.array([r[0] for r in Rc])
    # repeated random feature splits: select on half A, judge on half B
    res = defaultdict(lambda: defaultdict(list))
    srng = np.random.RandomState(4)
    for sp in range(200):
        perm = srng.permutation(len(keys)); A, B = perm[:len(keys) // 2], perm[len(keys) // 2:]
        for tname, tv in target.items():
            dA = (np.abs(feats[:, A] - tv[A]) / scale[A]).mean(1)
            dB = (np.abs(feats[:, B] - tv[B]) / scale[B]).mean(1)
            for s in SRC:
                m = srcs == s
                best = np.argsort(np.where(m, dA, np.inf))[:5]   # 5 best on A
                res[tname][s].append(float(dB[best].mean()))
    summary = {}
    for tname in target:
        summary[tname] = {s: float(np.mean(v)) for s, v in res[tname].items()}
        win = Counter(min(SRC, key=lambda s: res[tname][s][i]) for i in range(200))
        summary[tname]['_win'] = dict(win)
        print(tname, summary[tname], flush=True)
    # real corpora distance to Voynich on all features, for scale
    dreal = sorted(((float((np.abs(cm[i] - target['V_ZL']) / scale).mean()), c) for i, c in enumerate(corpora)))[:5]
    L.save('cycle4.json', {'summary': summary, 'dreal': dreal, 'cands': [(r[0], r[2]) for r in Rc]})
    planted_ok = sum(1 for t in target if t.startswith('P_') and max(summary[t]['_win'], key=summary[t]['_win'].get) == t.split('_')[1])
    npl = sum(1 for t in target if t.startswith('P_'))
    L.row(FN, 'V-31.4a', f'Planted control: {npl} targets made by the copy-and-vary procedure from a known vocabulary with hidden parameters; {len(Rc)} random candidates '
          f'({NC} per vocabulary) selected on a random half of the features, judged on the other half (200 splits)',
          '; '.join(f"{t}: winner {max(summary[t]['_win'], key=summary[t]['_win'].get)} {summary[t]['_win']}" for t in target if t.startswith('P_')),
          f'{planted_ok}/{npl} planted vocabularies recovered' + (' - method can tell vocabularies apart' if planted_ok >= 0.75 * npl else ' - method CANNOT reliably tell vocabularies apart'))
    for t in ('V_ZL', 'V_IT'):
        s = summary[t]
        L.row(FN, 'V-31.4b' if t == 'V_ZL' else 'V-31.4c', f'Voynich {t[2:]}: which vocabulary, pushed through the best copy-and-vary procedure, comes closest on held-out features (mean robust distance, lower = closer)',
              ', '.join(f'{k} {v:.2f}' for k, v in s.items() if k != '_win') + f"; split wins {s['_win']}; nearest real corpora (all features): " + ', '.join(f'{c} {d:.2f}' for d, c in dreal),
              f"best vocabulary {min((k for k in s if k != '_win'), key=s.get)}")


def _init():
    global SRC
    SRC = vocab_sources()


if __name__ == '__main__':
    main()
