"""v9 cycle 1: is each Voynich word dialled from a volvelle with a simple turning rule?

Corpora: planted (generated by a known 3-ring volvelle, Voynich line lengths),
Voynich ZL3b, Latin (Isidore) and Italian (Manzoni) under verbose substitution.
Each corpus: own 3-slot grammar (prefix / core / suffix rings), 12 commonest
fillers + OTHER per ring; train = alternate pages, test = the others.
Per ring, held-out log-likelihood of:
  M0  start distribution + iid fillers (no sequence)
  M1  within-ring Markov-1 (+ start distribution)
  M2  within-ring Markov-2
  VR  volvelle, n cells (n = 20/30/40/48), learned step kernel (rule R1), reset at each line;
      search = Baum-Welch on the circulant HMM with free per-cell emissions (the 'soft'
      volvelle), then hardened to one filler per cell and refitted (the true volvelle)
  VN  same ring, turning continues across line breaks (no reset)
Word level: product of rings vs word Markov-2 (trigram) on filler tuples.
Checkpoints: data/results/v9/c1_<corpus>_<ring>_<seed>.pkl
"""
import sys, os, pickle, time
sys.path.insert(0, os.path.dirname(__file__))
from v9_lib import *
from multiprocessing import Pool

OUT = os.path.join(RES, 'v9'); os.makedirs(OUT, exist_ok=True)
K, M, SIZES, ITERS, SEEDS = 3, 12, (20, 30, 40, 48), 150, (0,)
CORPORA = ('planted', 'voynich', 'vs_latin', 'vs_italian')


def planted_volvelle(lens, S=13, n=20, seed=11):
    """Ground truth: 3 rings of n cells, Zipf-ish labels, kernel 0.5 on step a, 0.2 on b, 0.3 spread."""
    rng = np.random.RandomState(seed)
    rings = []
    for k in range(K):
        p = 1 / np.arange(1, S + 1) ** 0.9
        lab = init_labels(p * 1000, n, rng)
        a, b = rng.choice(np.arange(1, n), 2, replace=False)
        q = np.full(n, 0.3 / n); q[a] += 0.5; q[b] += 0.2
        pi = rng.dirichlet(np.ones(n) * 0.3)
        rings.append((np.array(lab), q, pi))
    T = int(max(lens))
    O = -np.ones((len(lens), T, K), dtype=np.int64)
    for l, ln in enumerate(lens):
        for k, (lab, q, pi) in enumerate(rings):
            s = rng.choice(n, p=pi)
            for t in range(ln):
                if t: s = (s + rng.choice(n, p=q)) % n
                O[l, t, k] = lab[s]
    return O, rings


def load(name):
    if name == 'planted':
        L = corpus('voynich')
        lens = np.array([len(x['words']) for x in L])
        O, truth = planted_volvelle(lens)
        return L, O, lens, None, truth
    L = corpus(name)
    m = slot_model_cached(name, L, K)
    O, lens, voc = encode(L, m, M)
    return L, O, lens, voc, None


_cache = {}
def data(name):
    if name not in _cache:
        L, O, lens, voc, truth = load(name)
        tr, te = split_pages(L)
        _cache[name] = (O, lens, voc, truth, tr, te)
    return _cache[name]


def job(args):
    """One (corpus, ring, ring size): soft-emission EM on the circulant HMM (search),
    harden to a true volvelle (one filler per cell), hard EM; held-out scores; no-reset refit."""
    name, k, n = args
    fn = os.path.join(OUT, 'c1_%s_%d_n%d.pkl' % (name, k, n))
    if os.path.exists(fn):
        return pickle.load(open(fn, 'rb'))
    O, lens, voc, truth, tr, te = data(name)
    S = M + 1
    otr, ote = O[tr, :, k], O[te, :, k]
    ztr, zte = np.zeros_like(otr), np.zeros_like(ote)
    t0 = time.time()
    best = None
    for seed in SEEDS:
        h, hll, sll = soft_em(otr, ztr, S, n, iters=ITERS, seed=seed)
        if best is None or hll > best[1]:
            best = (h, hll, sll)
    h, hll, sll = best
    soft_te = forward_backward(h.soft, ote, zte, None, True)[0]
    hard_te = forward_backward(h, ote, zte, None, True)[0]
    rn = Ring(h.lab, S); rn.q = h.q.copy(); rn.pi = h.pi.copy()
    nr_tr = em(rn, otr, ztr, None, reset=False, iters=10)
    nr_te = forward_backward(rn, ote, zte, None, False)[0]
    res = dict(name=name, k=k, n=n, lab=h.lab.tolist(), q=h.q.tolist(), pi=h.pi.tolist(),
               soft_tr=sll, soft_te=soft_te, hard_tr=hll, hard_te=hard_te,
               noreset_tr=nr_tr, noreset_te=nr_te, q_noreset=rn.q.tolist(), secs=time.time() - t0)
    pickle.dump(res, open(fn, 'wb'))
    print('done', name, k, n, 'soft', round(sll), round(soft_te), 'hard', round(hll), round(hard_te),
          'noreset_te', round(nr_te), round(time.time() - t0), 's', flush=True)
    return res


def baselines(name):
    O, lens, voc, truth, tr, te = data(name)
    S = M + 1
    out = {'ntok_te': int((O[te, :, 0] >= 0).sum())}
    for k in range(K):
        for o in (0, 1, 2):
            ll, n, p = markov_ll(O[tr, :, k], O[te, :, k], S, order=o)
            out['M%d_%d' % (o, k)] = (ll, p)
    T_tr, T_te = tuples(O[tr]), tuples(O[te])
    out['W2'] = word_markov2(T_tr, T_te)
    out['W2p'] = word_markov2(T_tr, T_te, prune=3)
    # tuple unigram (no sequence, but full within-word dependence)
    c = Counter(w for L in T_tr for w in L); N = sum(c.values()); V = len(c) + 1
    out['W0'] = (sum(math.log((c[w] + 0.5) / (N + 0.5 * V)) for L in T_te for w in L), len(c))
    if truth is not None:   # oracle likelihood of the true volvelle on test
        oll = 0
        for k, (lab, q, pi) in enumerate(truth):
            r = Ring(lab, S); r.q = q[None, :]; r.pi = pi
            oll_k = forward_backward(r, O[te, :, k], np.zeros_like(O[te, :, k]), None, True)[0]
            out['oracle_%d' % k] = oll_k
    return out


if __name__ == '__main__':
    # big rings first so the two workers stay balanced
    jobs = [(c, k, n) for n in sorted(SIZES, reverse=True) for c in CORPORA for k in range(K)]
    with Pool(2) as P:
        res = P.map(job, jobs, chunksize=1)
    base = {c: baselines(c) for c in CORPORA}
    pickle.dump({'res': res, 'base': base}, open(os.path.join(OUT, 'c1_all.pkl'), 'wb'))
    print('ALL DONE')
