#!/usr/bin/env python3
"""LA-14 shared code: THE FORGERY CONTEST.

Do not model Linear A; forge it. Forgers of rising power are trained on one half of the real
documents (half A); discriminators try to tell the other half (half B) from forgeries under
5-fold cross-validation. What a discriminator still uses to catch the best forger is structure
that the forger's model class does not explain.

Document = list of word-level tokens:
  'W:KU-RO' word (sign string), 'L:GRA' logogram, 'N:197' integer, 'F:J' fraction letter,
  'NL' new line, 'DV' divider.
Sign stream (for sign-level forgers): words become 'S:KU','S:RO','/' .

Corpora: LA (tablets, lames, bars with >= 4 content tokens), LB (DAMOS, size-matched sample),
PLA (planted: real LA with an injected long-range agreement), FW_<forger> (a world generated by a
forger itself, the negative control).
"""
import json, math, os, random, re, unicodedata
from collections import Counter, defaultdict
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(HERE, '..', 'data')
OUT = os.path.join(D, 'la14')
os.makedirs(OUT, exist_ok=True)
SUPPORTS = {'Tablet', 'Lames (short thin tablet)', '3-sided bar', '4-sided bar'}

# ------------------------------------------------------------------ corpora

def ctoks(doc):
    return [t for t in doc if t not in ('NL', 'DV')]


def tidy(doc):
    out = []
    for t in doc:
        if t == 'NL' and (not out or out[-1] == 'NL'): continue
        out.append(t)
    while out and out[-1] in ('NL', 'DV'): out.pop()
    while out and out[0] in ('NL', 'DV'): out.pop(0)
    return out


SITE = {}  # document text -> site prefix (used by the E_wordsite forger)


def load_la():
    c = json.load(open(os.path.join(D, 'corpus.json')))
    docs, ids = [], []
    for r in c:
        if r['support'] not in SUPPORTS: continue
        d = []
        for t in r['tokens']:
            if t['t'] == 'word': d.append('W:' + '-'.join(t['s']))
            elif t['t'] == 'logo': d.append('L:' + t['v'])
            elif t['t'] == 'num':
                if t['v'] > 0 or not t['frac']: d.append('N:%d' % t['v'])
                for f in t['frac']: d.append('F:' + f)
            elif t['t'] == 'nl': d.append('NL')
            elif t['t'] == 'div': d.append('DV')
        d = tidy(d)
        if len(ctoks(d)) >= 4:
            docs.append(d); ids.append(r['id']); SITE[' '.join(d)] = r['id'][:2]
    return docs, ids


LB_UNITS = set('TVZSMNPQ')


def _clean_lb(t):
    t = unicodedata.normalize('NFD', t)
    t = ''.join(ch for ch in t if unicodedata.category(ch) != 'Mn')
    t = re.sub(r"[\[\]⟦⟧⌞⌟⸢⸣'\"?!<>{}]", '', t)
    return t.strip('-')


def load_lb(n=285, seed=0):
    docs = []
    for line in open(os.path.join(D, 'damos_items.jsonl')):
        x = json.loads(line)
        if not x.get('content'): continue
        d = []
        for ln in x['content'].split('\n'):
            ln = ln.strip()
            if not ln: continue
            if d: d.append('NL')
            for raw in ln.split():
                if raw.startswith('.') or raw in (',', '/', '//', ':'): continue
                t = _clean_lb(raw)
                if not t or t.endswith('.') or '.' in t: continue
                if t.lower() in ('vacat', 'vac', 'lat', 'sup', 'inf', 'mut', 'vest', 'deest', 'fr',
                                 'supra', 'infra', 'sigillum', 'v', 'verso', 'recto', 'margo', 'textus'):
                    continue
                if any('Ͱ' <= ch <= 'Ͽ' for ch in t): continue
                if re.fullmatch(r'\d+', t): d.append('N:%s' % t); continue
                if t in LB_UNITS: d.append('F:' + t); continue
                if any(ch.islower() for ch in t):
                    if not re.fullmatch(r'[a-z0-9*\-]+', t): continue
                    s = [p for p in t.split('-') if p]
                    if not s: continue
                    d.append('W:' + '-'.join(s).upper()); continue
                if re.fullmatch(r"[A-Z*0-9;+±:]+", t): d.append('L:' + t); continue
        d = tidy(d)
        if len(ctoks(d)) >= 4 and any(t.startswith('W:') for t in d) and len(d) <= 120:
            docs.append(d); SITE[' '.join(d)] = x['heading'][:2]
    rng = random.Random(seed)
    rng.shuffle(docs)
    return docs[:n]


def plant_agreement(docs, seed=5):
    """PLA: the first sign of the first word fixes the first sign of the LAST word (a hidden key
    map from 'head sign' to 'tail sign'). Applies to every doc with >= 2 words."""
    rng = random.Random(seed)
    signs = sorted({s for d in docs for t in d if t.startswith('W:') for s in t[2:].split('-')})
    common = [s for s, _ in Counter(s for d in docs for t in d if t.startswith('W:')
                                    for s in t[2:].split('-')).most_common(40)]
    key = {s: rng.choice(common) for s in signs}
    out = []
    for d in docs:
        d = list(d)
        wi = [i for i, t in enumerate(d) if t.startswith('W:')]
        if len(wi) >= 2:
            h = d[wi[0]][2:].split('-')[0]
            last = d[wi[-1]][2:].split('-')
            last[0] = key[h]
            d[wi[-1]] = 'W:' + '-'.join(last)
        out.append(d)
    return out, key


# ------------------------------------------------------------------ sign stream

def to_stream(doc):
    s = []
    for t in doc:
        if t.startswith('W:'):
            s.extend('S:' + x for x in t[2:].split('-')); s.append('/')
        else: s.append(t)
    return s


def from_stream(s):
    d, cur = [], []
    for t in s:
        if t.startswith('S:'): cur.append(t[2:]); continue
        if cur: d.append('W:' + '-'.join(cur)); cur = []
        if t == '/': continue
        d.append(t)
    if cur: d.append('W:' + '-'.join(cur))
    return tidy(d)


# ------------------------------------------------------------------ forgers

class Markov:
    """Order-k Markov chain with interpolated backoff (Witten-Bell-like) over a token stream."""
    def __init__(self, seqs, k):
        self.k = k
        self.c = [defaultdict(Counter) for _ in range(k + 1)]
        for s in seqs:
            s = ['<s>'] * k + list(s) + ['</s>']
            for i in range(k, len(s)):
                for j in range(k + 1):
                    self.c[j][tuple(s[i - j:i])][s[i]] += 1
        self.cache = {}

    def dist(self, ctx):
        key = tuple(ctx)
        if key in self.cache: return self.cache[key]
        p = Counter()
        for tok, n in self.c[0][()].items(): p[tok] = n
        tot = sum(p.values()); p = {t: v / tot for t, v in p.items()}
        for j in range(1, self.k + 1):
            cc = self.c[j].get(tuple(ctx[len(ctx) - j:]))
            if not cc: break
            n = sum(cc.values()); u = len(cc); lam = n / (n + u)
            p = {t: (1 - lam) * v for t, v in p.items()}
            for t, v in cc.items(): p[t] = p.get(t, 0) + lam * v / n
        toks = list(p); w = np.array([p[t] for t in toks]); w = w / w.sum()
        self.cache[key] = (toks, np.cumsum(w))
        return self.cache[key]

    def sample(self, rng, maxlen=150):
        ctx = ['<s>'] * self.k; out = []
        while len(out) < maxlen:
            toks, cw = self.dist(ctx[len(ctx) - self.k:] if self.k else [])
            t = toks[min(int(np.searchsorted(cw, rng.random())), len(toks) - 1)]
            if t == '</s>': break
            if t == '<s>': continue
            out.append(t); ctx.append(t)
        return out


def kind(t):
    if t.startswith('W:'): return 'W1' if '-' not in t else 'W2'
    if t in ('NL', 'DV'): return t
    return t[0]


class Unigram:
    def __init__(self, seqs):
        self.c = Counter(t for s in seqs for t in s); self.lens = [len(s) for s in seqs]
        self.toks = list(self.c); w = np.array([self.c[t] for t in self.toks], float)
        self.cw = np.cumsum(w / w.sum())

    def sample(self, rng):
        n = rng.choice(self.lens)
        return [self.toks[min(int(np.searchsorted(self.cw, rng.random())), len(self.toks) - 1)] for _ in range(n)]


class FlatGrammar:
    """Reimplementation of the la8 flat form: an order-2 chain over token kinds
    (W1, W2, L, N, F, NL, DV) with emissions drawn per kind; numbers drawn conditional on the
    kind of the previous token; words of novel type made by a sign-bigram chain at the
    training hapax rate."""
    def __init__(self, docs):
        self.kc = Markov([[kind(t) for t in d] for d in docs], 2)
        self.em = defaultdict(Counter); self.num = defaultdict(Counter)
        for d in docs:
            prev = '<s>'
            for t in d:
                k = kind(t)
                if k == 'N': self.num[prev][t] += 1
                else: self.em[k][t] += 1
                prev = k
        wc = Counter(t for d in docs for t in d if t.startswith('W:'))
        self.hapax = sum(1 for v in wc.values() if v == 1) / max(1, sum(wc.values()))
        self.sm = Markov([t[2:].split('-') for t in wc.elements()], 1)
        self._cum = {}

    def _draw(self, rng, cnt, key):
        if key not in self._cum:
            toks = list(cnt); w = np.array([cnt[t] for t in toks], float)
            self._cum[key] = (toks, np.cumsum(w / w.sum()))
        toks, cw = self._cum[key]
        return toks[min(int(np.searchsorted(cw, rng.random())), len(toks) - 1)]

    def sample(self, rng):
        ks = self.kc.sample(rng); out = []; prev = '<s>'
        for k in ks:
            if k == 'N':
                c = self.num.get(prev) or self.num['W2'] or Counter({'N:1': 1})
                out.append(self._draw(rng, c, 'N|' + prev))
            elif k in ('W1', 'W2') and rng.random() < self.hapax:
                for _ in range(20):
                    w = self.sm.sample(rng, 8)
                    if (k == 'W1') == (len(w) == 1) and w: break
                out.append('W:' + '-'.join(w) if w else self._draw(rng, self.em[k], k))
            elif k in ('NL', 'DV'): out.append(k)
            else:
                if not self.em[k]: continue
                out.append(self._draw(rng, self.em[k], k))
            prev = k
        return tidy(out)


class NeuralLM:
    """Small neural sequence model: a feed-forward neural LM (one hidden layer of 96 tanh units,
    window of 8 previous symbols, one-hot) over the sign stream, sampled autoregressively."""
    def __init__(self, docs, seed=0, win=8):
        from sklearn.neural_network import MLPClassifier
        from scipy import sparse
        self.win = win
        seqs = [to_stream(d) for d in docs]
        c = Counter(t for s in seqs for t in s)
        self.vocab = ['<pad>', '<s>', '</s>', '<unk>'] + sorted(t for t, n in c.items() if n >= 2)
        self.ix = {t: i for i, t in enumerate(self.vocab)}
        X, y = [], []
        for s in seqs:
            s2 = ['<s>'] + s + ['</s>']
            ids = [self.ix.get(t, 3) for t in s2]
            for i in range(1, len(ids)):
                ctx = ids[max(0, i - win):i]; ctx = [0] * (win - len(ctx)) + ctx
                X.append(ctx); y.append(ids[i])
        self.V = len(self.vocab)
        self.sp = sparse
        Xs = self._enc(np.array(X))
        self.m = MLPClassifier(hidden_layer_sizes=(96,), activation='tanh', alpha=1e-3,
                               max_iter=40, random_state=seed, early_stopping=False)
        self.m.fit(Xs, np.array(y))
        self.cls = self.m.classes_

    def _enc(self, X):
        n = X.shape[0]
        rows = np.repeat(np.arange(n), self.win)
        cols = (X + np.arange(self.win)[None, :] * self.V).ravel()
        return self.sp.csr_matrix((np.ones(len(cols)), (rows, cols)), shape=(n, self.win * self.V))

    def sample_many(self, rng, n, maxlen=150):
        ctxs = [[0] * (self.win - 1) + [1] for _ in range(n)]
        outs = [[] for _ in range(n)]; alive = list(range(n))
        pad_unk = {self.ix['<unk>'], 1, 0}
        for _ in range(maxlen):
            if not alive: break
            P = self.m.predict_proba(self._enc(np.array([ctxs[i][-self.win:] for i in alive])))
            nxt = []
            for row, i in zip(P, alive):
                p = row.copy()
                for j, cl in enumerate(self.cls):
                    if cl in pad_unk: p[j] = 0
                p /= p.sum()
                t = self.cls[min(int(np.searchsorted(np.cumsum(p), rng.random())), len(p) - 1)]
                if t == 2: continue
                outs[i].append(self.vocab[t]); ctxs[i].append(t); nxt.append(i)
            alive = nxt
        return [from_stream(o) for o in outs]


# ------------------------------------------------------------------ copy-edit forgers

def lines_of(d):
    L, cur = [], []
    for t in d:
        if t == 'NL': L.append(cur); cur = []
        else: cur.append(t)
    L.append(cur)
    return L


def join_lines(L):
    out = []
    for i, l in enumerate(L):
        if i: out.append('NL')
        out.extend(l)
    return tidy(out)


class CopyEdit:
    """Copies a real (half-A) document and applies one local edit of a given type."""
    TYPES = ['COPY0', 'E_num', 'E_numnear', 'E_word', 'E_logo', 'E_first', 'E_last', 'E_swapadj',
             'E_swapline', 'E_splice', 'E_numshuf', 'E_wordshuf', 'E_splLine', 'E_wordsite', 'E_splLM', 'E_splPair']

    def __init__(self, docs, etype):
        self.docs = docs; self.e = etype
        self.words = [t for d in docs for t in d if t.startswith('W:')]
        self.logos = [t for d in docs for t in d if t.startswith('L:')]
        self.nums = [t for d in docs for t in d if t.startswith('N:')]
        self.sitewords = defaultdict(list)
        for d in docs:
            st = SITE.get(' '.join(d), '??')
            self.sitewords[st] += [t for t in d if t.startswith('W:')]

    def ok(self, d):
        e = self.e
        if e in ('E_num', 'E_numnear'): return any(t.startswith('N:') for t in d)
        if e == 'E_numshuf': return len({t for t in d if t.startswith('N:')}) >= 2
        if e in ('E_word', 'E_first', 'E_last'): return any(t.startswith('W:') for t in d)
        if e == 'E_wordsite': return any(t.startswith('W:') for t in d) and len(self.sitewords.get(SITE.get(' '.join(d), '??'), [])) >= 30
        if e in ('E_splLine', 'E_splLM', 'E_splPair'): return len([l for l in lines_of(d) if l]) >= 3
        if e == 'E_wordshuf': return len({t for t in d if t.startswith('W:')}) >= 2
        if e == 'E_logo': return any(t.startswith('L:') for t in d)
        if e == 'E_swapline': return len([l for l in lines_of(d) if l]) >= 3
        if e == 'E_splice': return len(ctoks(d)) >= 6
        if e == 'E_swapadj': return len(ctoks(d)) >= 3
        return True

    def sample(self, rng):
        cand = [d for d in self.docs if self.ok(d)]
        if not getattr(self, 'queue', None):
            self.queue = list(range(len(self.docs))); rng.shuffle(self.queue)
            self.queue = [i for i in self.queue if self.ok(self.docs[i])]
            self.queue_all = list(self.queue)
        self.src = self.queue.pop()
        for _ in range(50):
            d = list(self.docs[self.src]); e = self.e
            if e == 'COPY0': return d
            if e in ('E_num', 'E_numnear'):
                i = rng.choice([i for i, t in enumerate(d) if t.startswith('N:')])
                v = int(d[i][2:])
                if e == 'E_num': nv = int(rng.choice(self.nums)[2:])
                else: nv = max(1, int(round(v * math.exp(rng.uniform(-0.7, 0.7)))) + rng.choice([-1, 1]) * (rng.random() < 0.3))
                if nv == v: continue
                d[i] = 'N:%d' % nv; return d
            if e in ('E_word', 'E_first', 'E_last'):
                wi = [i for i, t in enumerate(d) if t.startswith('W:')]
                i = wi[0] if e == 'E_first' else wi[-1] if e == 'E_last' else rng.choice(wi)
                w = rng.choice(self.words)
                if w == d[i]: continue
                d[i] = w; return d
            if e == 'E_wordsite':
                i = rng.choice([i for i, t in enumerate(d) if t.startswith('W:')])
                w = rng.choice(self.sitewords[SITE.get(' '.join(self.docs[self.src]), '??')])
                if w == d[i]: continue
                d[i] = w; return d
            if e == 'E_splLine':
                d2 = self.docs[rng.choice(self.queue_all)]
                if d2 == d: continue
                L1 = lines_of(d); L2 = lines_of(d2)
                i = rng.randint(1, len(L1) - 1); j = rng.randint(1, max(1, len(L2) - 1))
                return join_lines(L1[:i] + L2[j:])
            if e == 'E_splLM':  # line splice that keeps the line count of the first tablet exactly
                L1 = lines_of(d); n1 = len(L1); i = rng.randint(1, n1 - 1); need = n1 - i
                pool = [k for k in self.queue_all if k != self.src and len(lines_of(self.docs[k])) >= need + 1]
                if not pool: continue
                L2 = lines_of(self.docs[rng.choice(pool)])
                return join_lines(L1[:i] + L2[len(L2) - need:])
            if e == 'E_logo':
                i = rng.choice([i for i, t in enumerate(d) if t.startswith('L:')])
                w = rng.choice(self.logos)
                if w == d[i]: continue
                d[i] = w; return d
            if e == 'E_swapadj':
                ci = [i for i, t in enumerate(d) if t not in ('NL', 'DV')]
                j = rng.randrange(len(ci) - 1); a, b = ci[j], ci[j + 1]
                if d[a] == d[b]: continue
                d[a], d[b] = d[b], d[a]; return d
            if e == 'E_swapline':
                L = lines_of(d); idx = [i for i, l in enumerate(L) if l]
                a, b = rng.sample(idx, 2)
                if L[a] == L[b]: continue
                L[a], L[b] = L[b], L[a]; return join_lines(L)
            if e == 'E_splice':
                d2 = rng.choice(cand)
                if d2 == d: continue
                ca = len(d); cb = len(d2)
                i = rng.randint(ca // 3, max(ca // 3, 2 * ca // 3)); j = rng.randint(cb // 3, max(cb // 3, 2 * cb // 3))
                return tidy(d[:i] + d2[j:])
            if e in ('E_numshuf', 'E_wordshuf'):
                p = 'N:' if e == 'E_numshuf' else 'W:'
                ii = [i for i, t in enumerate(d) if t.startswith(p)]
                vals = [d[i] for i in ii]; v2 = vals[:]; rng.shuffle(v2)
                if v2 == vals: continue
                for i, v in zip(ii, v2): d[i] = v
                return d
        return list(self.docs[self.src])


GEN_FORGERS = ['UNI', 'MK1', 'MK2', 'MK3', 'MK4', 'WMK1', 'WMK2', 'FLAT', 'NEUR']


def make_forger(name, docs, seed=0):
    if name == 'UNI': return Unigram([to_stream(d) for d in docs]), 'stream'
    if name.startswith('MK'): return Markov([to_stream(d) for d in docs], int(name[2:])), 'stream'
    if name.startswith('WMK'): return Markov(docs, int(name[3:])), 'word'
    if name == 'FLAT': return FlatGrammar(docs), 'word'
    if name == 'NEUR': return NeuralLM(docs, seed=seed), 'neural'
    return CopyEdit(docs, name), 'word'


def forge(name, docs, n, seed):
    """Returns (forgeries, groups). Groups: identical forgeries share a group; copy-edit forgeries
    carry their source document, so CV never splits a source between train and test."""
    rng = random.Random(seed * 7919 + sum(map(ord, name)) * 31)
    f, mode = make_forger(name, docs, seed)
    out, grp = [], []
    if mode == 'neural':
        nrng = np.random.RandomState(seed)
        class R:
            def random(self): return nrng.random_sample()
        while len(out) < n:
            out += [d for d in f.sample_many(R(), n) if len(ctoks(d)) >= 4]
        out = out[:n]
    elif name == 'E_splPair':
        # leak-free splice: tablets are paired without replacement; each pair (a, b) gives a-head + b-tail and
        # b-head + a-tail, each with the line count of its head tablet; both forgeries share one CV group
        q = [d for d in docs if f.ok(d)]; rng.shuffle(q)
        for p in range(0, len(q) - 1, 2):
            a, b = lines_of(q[p]), lines_of(q[p + 1]); na, nb = len(a), len(b)
            i = rng.randint(max(1, na - nb + 1), na - 1); j = rng.randint(max(1, nb - na + 1), nb - 1)
            out += [join_lines(a[:i] + b[nb - (na - i):]), join_lines(b[:j] + a[na - (nb - j):])]
            grp += ['pair%d' % p] * 2
        return out[:n], grp[:n]
    elif isinstance(f, CopyEdit):
        nmax = sum(1 for d in docs if f.ok(d)); n = min(n, nmax)
        for _ in range(n):
            out.append(f.sample(rng)); grp.append('src%d' % f.src)
        return out, grp
    else:
        tries = 0
        while len(out) < n and tries < n * 50:
            tries += 1
            s = f.sample(rng)
            d = from_stream(s) if mode == 'stream' else tidy(s)
            if len(ctoks(d)) >= 4: out.append(d)
    seen = {}
    for d in out: grp.append('g%d' % seen.setdefault(' '.join(d), len(seen)))
    return out, grp


def real_for(name, B):
    """Real half-B documents eligible for the forger (copy-edit forgers need an editable slot)."""
    if name in CopyEdit.TYPES:
        ce = CopyEdit(B, name); return [d for d in B if ce.ok(d)]
    return B


# ------------------------------------------------------------------ features

def nb(v):
    return 'n%d' % v if v <= 10 else 'n2^%d' % int(math.log2(v))


def ab(t):
    return nb(int(t[2:])) if t.startswith('N:') else t


def cls(t):
    if t.startswith('W:'): return 'W'
    return t if t in ('NL', 'DV') else t[0]


def _nums(d):
    return [int(t[2:]) for t in d if t.startswith('N:')]


def f_len(d):
    c = ctoks(d); L = [l for l in lines_of(d) if l]; ll = [len(l) for l in L] or [0]
    k = Counter(cls(t) for t in d)
    W = [t for t in d if t.startswith('W:')]
    return {'ntok': math.log1p(len(c)), 'nlines': math.log1p(len(L)), 'llmean': np.mean(ll), 'llsd': np.std(ll),
            'llmax': max(ll), 'fW': k['W'] / len(c), 'fL': k['L'] / len(c), 'fN': k['N'] / len(c),
            'fF': k['F'] / len(c), 'fDV': k['DV'] / len(c),
            'w1': sum('-' not in w for w in W) / max(1, len(W)),
            'wlen': np.mean([w.count('-') + 1 for w in W]) if W else 0}


def f_uni(d):
    return dict(Counter('u=' + ab(t) for t in ctoks(d)))


def f_sign(d):
    c = Counter()
    for t in d:
        if t.startswith('W:'):
            s = t[2:].split('-'); c['wl=%d' % min(len(s), 6)] += 1
            for x in s: c['s=' + x] += 1
    return dict(c)


def f_sbig(d):
    c = Counter()
    for t in d:
        if t.startswith('W:'):
            s = t[2:].split('-'); c['i=' + s[0]] += 1; c['f=' + s[-1]] += 1
            for a, b in zip(s, s[1:]): c['b=%s_%s' % (a, b)] += 1
    return dict(c)


def f_tbig(d):
    c = Counter(); a = [ab(t) for t in d]; k = [cls(t) for t in d]
    for i in range(len(d) - 1):
        c['tb=%s_%s' % (a[i], a[i + 1])] += 1; c['cb=%s_%s' % (k[i], k[i + 1])] += 1
    for i in range(len(d) - 2): c['ct=%s_%s_%s' % tuple(k[i:i + 3])] += 1
    return dict(c)


def f_pos(d):
    c = ctoks(d); L = [l for l in lines_of(d) if l]
    r = {'p0=' + ab(c[0]): 1, 'p1=' + ab(c[1]): 1, 'pE=' + ab(c[-1]): 1, 'pE2=' + ab(c[-2]): 1,
         'fl=' + '_'.join(cls(t) for t in L[0])[:20]: 1, 'll=' + '_'.join(cls(t) for t in L[-1])[:20]: 1}
    n = len(c)
    for i, t in enumerate(c):
        k = 'pc%d=%s' % (min(2, 3 * i // n), cls(t)); r[k] = r.get(k, 0) + 1
    for i, l in enumerate(L):
        if l and l[0].startswith('W:'):
            k = 'lw%d=%s' % (0 if i == 0 else 2 if i == len(L) - 1 else 1, l[0]); r[k] = r.get(k, 0) + 1
    return r


def f_arith(d):
    v = _nums(d); r = {}
    if not v: return {'nonum': 1}
    s = sum(v); n = len(v)
    r['tot_last'] = float(n >= 3 and v[-1] == sum(v[:-1]))
    r['tot_all'] = float(n >= 3 and any(2 * x == s for x in v))
    run = 0
    for i in range(2, n):
        for j in range(0, i - 1):
            if sum(v[j:i]) == v[i]: run += 1; break
    r['tot_run'] = run / n
    r['max_last'] = float(v[-1] == max(v) and n >= 2)
    r['maxshare'] = max(v) / s if s else 0
    r['distinct'] = len(set(v)) / n
    r['ones'] = v.count(1) / n
    r['round10'] = sum(x % 10 == 0 and x > 0 for x in v) / n
    lv = [math.log1p(x) for x in v]
    r['lmean'] = np.mean(lv); r['lsd'] = np.std(lv)
    r['desc'] = sum(b <= a for a, b in zip(v, v[1:])) / max(1, n - 1)
    r['near_last'] = float(n >= 3 and abs(v[-1] - sum(v[:-1])) <= max(1, 0.05 * v[-1]))
    return r


def f_numw(d):
    r = Counter(); prs = []
    for a, b in zip(d, d[1:]):
        if b.startswith('N:'):
            v = int(b[2:]); r['nw=%s|%s' % (ab(a), nb(v))] += 1; r['nc=%s|%s' % (cls(a), nb(v))] += 1
            if a.startswith('W:'): prs.append((a.count('-') + 1, math.log1p(v)))
    r = dict(r)
    if len(prs) >= 3 and np.std([p[0] for p in prs]) > 0 and np.std([p[1] for p in prs]) > 0:
        r['wl_corr'] = float(np.corrcoef(np.array(prs).T)[0, 1])
    return r


def f_long(d):
    c = ctoks(d); W = [t for t in c if t.startswith('W:')]; Ls = [t for t in c if t.startswith('L:')]
    r = Counter()
    if W:
        fs = W[0][2:].split('-')[0]
        for t in c[2:]:
            if t.startswith('W:'): r['h=%s>S%s' % (fs, t[2:].split('-')[0])] += 1
            elif t.startswith('L:'): r['h=%s>%s' % (fs, t)] += 1
        if len(W) >= 2:
            r['hl=%s>%s' % (fs, W[-1][2:].split('-')[0])] += 1
            r['hlw=%s>%s' % (W[0], W[-1])] += 1
            r['same_fs'] = sum(w[2:].split('-')[0] == fs for w in W[1:]) / (len(W) - 1)
            r['same_ls'] = sum(w.split('-')[-1] == W[0].split('-')[-1] for w in W[1:]) / (len(W) - 1)
    if Ls:
        for t in Ls[1:]: r['Lh=%s>%s' % (Ls[0], t)] += 1
        r['nLdist'] = len(set(Ls)); r['Lsame'] = Ls.count(Ls[0]) / len(Ls)
    return dict(r)


def f_rep(d):
    c = ctoks(d); W = [t for t in c if t.startswith('W:')]; L = [l for l in lines_of(d) if l]
    tpl = ['_'.join(cls(t) for t in l) for l in L]
    r = {'wdist': len(set(W)) / max(1, len(W)), 'wmaxrep': max(Counter(W).values()) if W else 0,
         'tokdist': len(set(c)) / len(c),
         'tplsame': sum(a == b for a, b in zip(tpl, tpl[1:])) / max(1, len(tpl) - 1),
         'tpldist': len(set(tpl)) / len(tpl)}
    bg = list(zip(c, c[1:])); r['bgrep'] = 1 - len(set(bg)) / max(1, len(bg))
    for t in set(tpl): r['lt=' + t[:24]] = tpl.count(t)
    return r


GROUPS = {'len': f_len, 'uni': f_uni, 'sign': f_sign, 'sbig': f_sbig, 'tbig': f_tbig, 'pos': f_pos,
          'arith': f_arith, 'numw': f_numw, 'long': f_long, 'rep': f_rep}
ALLG = list(GROUPS) + ['ngram']


def featurize(docs, groups):
    rows = []
    for d in docs:
        r = {}
        for g in groups:
            if g == 'ngram': continue
            for k, v in GROUPS[g](d).items(): r[g + ':' + k] = float(v)
        rows.append(r)
    return rows


def ngram_strings(docs):
    return [' '.join(x.replace(':', '').replace('/', '_') for x in to_stream([ab(t) for t in d])) for d in docs]


# ------------------------------------------------------------------ discriminators

def make_clf(name, rs):
    from sklearn.linear_model import LogisticRegression
    from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
    from sklearn.neural_network import MLPClassifier
    if name == 'LR': return LogisticRegression(C=0.3, max_iter=2000, solver='liblinear')
    if name == 'LR10': return LogisticRegression(C=3.0, max_iter=2000, solver='liblinear')
    if name == 'RF': return RandomForestClassifier(n_estimators=100, min_samples_leaf=2, random_state=rs, n_jobs=1)
    if name == 'HGB': return HistGradientBoostingClassifier(max_iter=40, learning_rate=0.1, random_state=rs)
    if name == 'MLP': return MLPClassifier(hidden_layer_sizes=(32,), alpha=1e-2, max_iter=150, random_state=rs)
    raise ValueError(name)


CLFS = ['LR', 'LR10', 'RF', 'HGB', 'MLP']


def build_X(real, fake, groups):
    from sklearn.feature_extraction import DictVectorizer
    from sklearn.feature_extraction.text import CountVectorizer
    from scipy import sparse
    docs = real + fake
    y = np.array([0] * len(real) + [1] * len(fake))
    mats, names = [], []
    dg = [g for g in groups if g != 'ngram']
    if dg:
        dv = DictVectorizer()
        X = dv.fit_transform(featurize(docs, dg)); mats.append(X); names += list(dv.get_feature_names_out())
    if 'ngram' in groups:
        cv = CountVectorizer(ngram_range=(1, 3), token_pattern=r'\S+', min_df=2, lowercase=False)
        X = cv.fit_transform(ngram_strings(docs)); mats.append(X); names += ['ngram:' + x for x in cv.get_feature_names_out()]
    X = sparse.hstack(mats).tocsr()
    # keep features that occur in >= 2 docs
    nz = np.asarray((X != 0).sum(0)).ravel(); keep = nz >= 2
    X = X[:, keep]; names = [n for n, k in zip(names, keep) if k]
    return X, y, names


def cv_auc(X, y, clfname, seed, coefs=False, groups=None):
    """5-fold stratified (group) CV AUC; scaling by max-abs; returns auc (and mean LR coefs)."""
    from sklearn.model_selection import StratifiedKFold, StratifiedGroupKFold
    from sklearn.preprocessing import MaxAbsScaler
    from sklearn.metrics import roc_auc_score
    if groups is None: groups = list(range(len(y)))
    skf = StratifiedGroupKFold(5, shuffle=True, random_state=seed)
    pred = np.zeros(len(y)); C = []
    if clfname in ('MLP', 'HGB'):  # costly learners see the most frequent columns only
        nz = np.asarray((X != 0).sum(0)).ravel(); top = np.argsort(-nz)[:300 if clfname == 'MLP' else 150]
        X = X[:, np.sort(top)]
    for tr, te in skf.split(np.zeros(len(y)), y, groups):
        sc = MaxAbsScaler().fit(X[tr]); Xtr = sc.transform(X[tr]); Xte = sc.transform(X[te])
        if clfname == 'HGB': Xtr = Xtr.toarray(); Xte = Xte.toarray()
        m = make_clf(clfname, seed).fit(Xtr, y[tr])
        pred[te] = m.predict_proba(Xte)[:, 1]
        if coefs and hasattr(m, 'coef_'): C.append(m.coef_.ravel())
    auc = roc_auc_score(y, pred)
    return (auc, np.mean(C, 0) if C else None) if coefs else auc


def split(docs, seed):
    idx = list(range(len(docs))); random.Random(seed).shuffle(idx)
    h = len(idx) // 2
    return [docs[i] for i in idx[:h]], [docs[i] for i in idx[h:]]


_CORP = {}


def corpus(name):
    if name in _CORP: return _CORP[name]
    if name == 'LA': c = load_la()[0]
    elif name == 'LB': c = load_lb(len(load_la()[0]))
    elif name == 'PLA': c = plant_agreement(load_la()[0])[0]
    elif name.startswith('FW_'):
        p = os.path.join(OUT, 'world_%s.json' % name)
        if not os.path.exists(p):
            src = corpus('LA')
            json.dump(forge(name[3:], src, len(src), 999)[0], open(p, 'w'))
        c = json.load(open(p))
    _CORP[name] = c
    return c
